import type { Metadata } from "next";
import "./globals.scss";
import UpButton from "@/components/UpButton";
import Layout from "@/featured/layout/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout>
          {children}
          <UpButton />
        </Layout>
      </body>
    </html>
  );
}
